#!/bin/bash
sam package   --template-file template.yaml   --output-template-file package.yml   --s3-bucket chesssam-titiloxx
sam deploy   --template-file package.yml   --stack-name chesscom   --capabilities CAPABILITY_IAM
rm package.yml